### ISSUE TITLE
syntax tweaks

### ISSUE THREAD

**Issue by y** [xuhdev/syntax-dosini.vim#1]
diff --git a/syntax/dosini.vim b/syntax/dosini.vim
    index a151852..4e5cbdc 100644
    --- a/syntax/dosini.vim
    +++ b/syntax/dosini.vim
    @@ -22,10 +22,11 @@ endif
    " shut case off
    syn case ignore
    
    -syn match  dosiniNumber   "\<\d\+\>"
    -syn match  dosiniNumber   "\<\d*\.\d\+\>"
    -syn match  dosiniNumber   "\<\d\+e[+-]\=\d\+\>"
    -syn match  dosiniLabel    "^.\{-}="
    +syn match  dosiniLabel    "^.\{-}\ze\s*=" nextgroup=dosiniNumber,dosiniValue
    +syn match  dosiniValue    "=\zs.*"
    +syn match  dosiniNumber   "=\zs\s*\d\+\s*$"
    +syn match  dosiniNumber   "=\zs\s*\d*\.\d\+\s*$"
    +syn match  dosiniNumber   "=\zs\s*\d\+e[+-]\=\d\+\s*$"
    syn region dosiniHeader   start="^\s*\[" end="\]"
    syn match  dosiniComment  "^[#;].*$"

* highlight values as numbers only if they encompass the whole value (avoids odd highlighting with values like dash-123-delimited-678-hash) .
* don't highlight the equal signs or trailing whitespace as part of the label.

**Comment by xuhdev** [comment]
Would you mind making a pull request ;)

**Comment by xuhdev** [comment]
Merged #2.
